[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "I", "N", "UP", "PL", "RUF"]
ignore = ["E501"]

[tool.djlint]
ignore = "H006,H021"

# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --cov=. --cov-report term-missing:skip-covered"
python_files = "tests.py"
DJANGO_SETTINGS_MODULE = "fedidevs.settings"

[tool.coverage.run]
plugins = ["django_coverage_plugin"]
omit = [".venv/*", "staticfiles/*", "manage.py", "requirements.txt", "fedidevs/wsgi.py", "fedidevs/asgi.py"]
