name: Upgrade dependencies

on:
  schedule:
  - cron: "0 10 * * MON"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
    - name: Upgrade dependencies
      run: |
        printf "### Upgraded dependencies\n\n\`\`\`\n" > update.log
        uv lock --upgrade 2>&1 | tee -a update.log
        printf "\`\`\`" >> update.log
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PAT }}
        commit-message: Upgrade dependencies
        branch: bot/upgrade-dependencies
        delete-branch: true
        title: 'Upgrade dependencies'
        body-path: update.log
